#!/bin/sh
VERSION=6.0.1
docker build --build-arg VERSION=$VERSION -t ghcr.io/omnetpp/omnetpp-gui:u22.05-$VERSION-SAC . && mkdir ~/omnetpp && cp ./opp_gui_docker_shell ~/omnetpp/ && cd ~/omnetpp && git clone https://github.com/omnetpp/omnetpp.git && mv omnetpp/samples . && rm -rf omnetpp

# Go to ~/omnetpp and launch ./opp_gui_docker_shell
# Remember to choos /root/models as default Workspace