#!/bin/sh
echo "Starting Omnetpp docker container..."
if [ "$XDG_SESSION_TYPE" = "x11" ]; then
    docker run --device /dev/dri/ --rm -it -v "$(pwd):/root/models" -u "$(id -u):$(id -g)" -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY ghcr.io/omnetpp/omnetpp-gui:u22.05-6.0.1-SAC
elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    xhost +SI:localuser:$(id -un)
    docker run --device /dev/dri/ --rm -it -v "$(pwd):/root/models" -u "$(id -u):$(id -g)" -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY ghcr.io/omnetpp/omnetpp-gui:u22.05-6.0.1-SAC
else
    echo "Are you kidding me???"
fi
