#!/bin/sh
echo "Starting Omnetpp docker container..."
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    xhost +SI:localuser:$(id -un)
fi
docker run --device /dev/dri/ --rm -it -v "$(pwd):/root/models" -u "$(id -u):$(id -g)" -v /tmp/.X11-unix:/tmp/.X11-unix --name omnet -e DISPLAY=unix$DISPLAY ghcr.io/omnetpp/omnetpp-gui:u22.05-6.0.2-SAC
