sudo: required
services:
  - docker
before_install:
  - docker build -t omnetpp/docker-sphinx .
script:
  - WORKDIR="$(mktemp -d)"
  - cd "${WORKDIR}"
  - docker run --rm -it -v "${PWD}:/doc" -u "$(id -u):$(id -g)" omnetpp/docker-sphinx sphinx-quickstart -q -p PROJECT -a AUTHOR
  - docker run --rm -it -v "${PWD}:/doc" -u "$(id -u):$(id -g)" omnetpp/docker-sphinx make html
notifications:
  email:
    on_success: never
    on_failure: always
